[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "bash download_models.sh && echo 'models done' && npm run db:push && echo 'db done' && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PYTHONUNBUFFERED = "1"
OPENCV_VIDEOIO_PRIORITY_MSMF = "0"
